#配置文件环境配置
spring:
  profiles:
    active: dev
    
  #jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

  #mongodb配置
  data:
    mongodb:
      url: mongodb://@localhost:27017/test

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379

  #sql Server 配置
  datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=student
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: 123456
  #jpa 配置
  jpa:
    database: sql_server
    show-sql: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

#log 日志配置
logging:
  config: classpath:logback-manage.xml

#端口
server: 
  port: 8888
#  context-path: /manage
    
---
spring:
  profiles: dev
server:
  port: 8080
  
---
spring:
  profiles: prod
server:
  port: 8082
  
---
spring:
  profiles: test
server:
  port: 8081
